### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by endercatone** [nxtrace/NTrace-core#144]
## 你正在使用哪个版本的 nexttrace？

linux_amd64

## 你看到的异常现象是什么？

运行报错:
```
NextTrace v1.1.7-2 2023-06-06T19:36:22Z b1edef3
[NextTrace API] prefered API IP - xxx.xxx.xxx.xxx - 59.20ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x750217]

goroutine 1 [running]:
github.com/tsosunchia/powclient.submitAnswer(0xc000155520, 0x49e780?)
        github.com/tsosunchia/powclient@v0.1.3/pow_client.go:142 +0x57
github.com/tsosunchia/powclient.RetToken(0xc0001555d8)
        github.com/tsosunchia/powclient@v0.1.3/pow_client.go:102 +0x252
github.com/xgadget-lab/nexttrace/pow.GetToken({0xc00024a000?, 0xc000155820?}, {0x8d760c, 0xb}, {0x8cc592?, 0x3?})
        github.com/xgadget-lab/nexttrace/pow/pow.go:29 +0x255
github.com/xgadget-lab/nexttrace/wshandle.createWsConn()
        github.com/xgadget-lab/nexttrace/wshandle/client.go:193 +0x1e5
github.com/xgadget-lab/nexttrace/wshandle.New(...)
        github.com/xgadget-lab/nexttrace/wshandle/client.go:243
github.com/xgadget-lab/nexttrace/cmd.Excute()
        github.com/xgadget-lab/nexttrace/cmd/cmd.go:161 +0x133d
main.main()
        github.com/xgadget-lab/nexttrace/main.go:8 +0x17
```

## 你期待看到的正常表现是怎样的？

正常输出

## 请附上你的命令

nexttrace xxx.xxx.xxx.xxx

## 请附上出错时软件输出的错误信息
```
nexttrace xxx.xxx.xxx.xxx
NextTrace v1.1.7-2 2023-06-06T19:36:22Z b1edef3
[NextTrace API] prefered API IP - 103.120.18.35 - 59.20ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x750217]

goroutine 1 [running]:
github.com/tsosunchia/powclient.submitAnswer(0xc000155520, 0x49e780?)
        github.com/tsosunchia/powclient@v0.1.3/pow_client.go:142 +0x57
github.com/tsosunchia/powclient.RetToken(0xc0001555d8)
        github.com/tsosunchia/powclient@v0.1.3/pow_client.go:102 +0x252
github.com/xgadget-lab/nexttrace/pow.GetToken({0xc00024a000?, 0xc000155820?}, {0x8d760c, 0xb}, {0x8cc592?, 0x3?})
        github.com/xgadget-lab/nexttrace/pow/pow.go:29 +0x255
github.com/xgadget-lab/nexttrace/wshandle.createWsConn()
        github.com/xgadget-lab/nexttrace/wshandle/client.go:193 +0x1e5
github.com/xgadget-lab/nexttrace/wshandle.New(...)
        github.com/xgadget-lab/nexttrace/wshandle/client.go:243
github.com/xgadget-lab/nexttrace/cmd.Excute()
        github.com/xgadget-lab/nexttrace/cmd/cmd.go:161 +0x133d
main.main()
        github.com/xgadget-lab/nexttrace/main.go:8 +0x17
```

## 是否查询过本仓库wiki有没有类似错误

未找到类似错误

---

我不确定其他电脑会不会报错

**Comment by catna** [comment]
mac 系统上面也会报同样的错

**Comment by isyekong** [comment]
目标IP是AWS的嘛？如果是，设置一下 max_hop再试试，添加参数 -m 50

**Comment by JohyC** [comment]
NextTrace v1.1.2 2023-02-20T05:07:06Z 88e69f7 
Windows Linux amd64 平台
报同样的错误，无效的内存地址....

**Comment by sjlleo** [comment]
> > 目标IP是AWS的嘛？如果是，设置一下 max_hop再试试，添加参数 -m 50
> 
> 测试任何ip均报错，添加参数无效

Hi endercatone,

这个问题是没能从我们的pow api成功领取任务，遗憾的是我们的api服务器已经在国内无法正常使用，我们尝试过更换新域名，但是很快再次被封禁，您可以根据wiki中提到的，设置我们官方提供的proxy来正常使用 nexttrace

```shell
export NEXTTRACE_HOSTPORT=nexttrace-io-leomoe-api-a0.shop
```

如果是Windows用户，可以使用NextTrace的GUI客户端例如OpenTrace直接在图形化界面设置Proxy。

Thanks
