### ISSUE TITLE
NextTrace v1.2.1.1 报错

### ISSUE THREAD

**Issue by Chennhaoo** [nxtrace/NTrace-core#163]
## 你正在使用哪个版本的 nexttrace？
NextTrace v1.2.1.1
CENTOS 7.9.2009 X64
VPS：185.213.24.**
这是瑞士的VPS，其他机器上没出过这个问题，请问这是数据库不通吗

## 你看到的异常现象是什么？
```
NextTrace v1.2.1.1 2023-09-07T08:38:12Z b967ee4
[NextTrace API] prefered API IP - 104.19.29.108 - 1.68ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x755a97]

goroutine 1 [running]:
github.com/tsosunchia/powclient.submitAnswer(0xc0000c3488, 0x49ef80?)
	github.com/tsosunchia/powclient@v0.1.3/pow_client.go:142 +0x57
github.com/tsosunchia/powclient.RetToken(0xc0000c3540)
	github.com/tsosunchia/powclient@v0.1.3/pow_client.go:102 +0x252
github.com/xgadget-lab/nexttrace/pow.GetToken({0xc0000285b8?, 0xb?}, {0x8e0569, 0xb}, {0x8d5430?, 0x991680?})
	github.com/xgadget-lab/nexttrace/pow/pow.go:29 +0x255
github.com/xgadget-lab/nexttrace/wshandle.createWsConn()
	github.com/xgadget-lab/nexttrace/wshandle/client.go:199 +0x1f4
github.com/xgadget-lab/nexttrace/wshandle.New(...)
	github.com/xgadget-lab/nexttrace/wshandle/client.go:255
github.com/xgadget-lab/nexttrace/cmd.Excute()
	github.com/xgadget-lab/nexttrace/cmd/cmd.go:166 +0x148b
main.main()
	github.com/xgadget-lab/nexttrace/main.go:8 +0x17
```

## 请附上你的命令

-g cn -q 1 -n -m 30 IP

**Comment by tsosunchia** [comment]
已经观察到【欧洲区域】访问我们的API出现问题
您可通过暂时修改hosts文件指定访问我们在其他地区的服务器以在我们修复欧洲节点之前保持访问
echo "45.88.195.154 api.leo.moe" >> /etc/hosts
